schoolwebsite/Models/Teachers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace schoolwebsite.Models
{
    public class Teachers

    {
        public Teachers()
        {
            DateCreated = DateTime.Now;
            
        }
        public int id { get; set; }
        
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMMM,dd  yyyy  hh:mm}")]
        public DateTime? DateCreated { get; set; }
        [Required(ErrorMessage = "Please give your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please give your email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please give your Contact Number")]
        public string ContactNum { get; set; }
        [Required(ErrorMessage = "Please give your Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please give a username for your account")]

        public string Username { get; set; }
        [Required(ErrorMessage = "Please give a correct password")]
        public string password { get; set; }

        


    }
}

schoolwebsite/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using schoolwebsite.Data;
using schoolwebsite.Models;

namespace schoolwebsite.Controllers
{
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeachersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Teachers.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers
                .FirstOrDefaultAsync(m => m.id == id);
            if (teachers == null)
            {
                return NotFound();
            }

            return View(teachers);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Email,ContactNum,Address,Username,password")] Teachers teachers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teachers);
                await _context.SaveChangesAsync();
                TempData["save"] = "Data saved Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(teachers);
        }
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]
        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers.FindAsync(id);
            if (teachers == null)
            {
                return NotFound();
            }
            return View(teachers);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Email,ContactNum,Address,Username,password")] Teachers teachers)
        {
            if (id != teachers.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teachers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeachersExists(teachers.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teachers);
        }
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Headmaster")]

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers
                .FirstOrDefaultAsync(m => m.id == id);
            if (teachers == null)
            {
                return NotFound();
            }

            return View(teachers);
        }

        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Headmaster")]
        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teachers = await _context.Teachers.FindAsync(id);
            _context.Teachers.Remove(teachers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public JsonResult Namecheck(string userdata)
        {
            var search = _context.Teachers.Any(e => e.Username == userdata);
            if (search)
            {
                return Json(1);
            }
            else { return Json(0); }
        }

        private bool TeachersExists(int id)
        {
            return _context.Teachers.Any(e => e.id == id);
        }
    }
}

schoolwebsite/Views/Teachers/Create.cshtml
@model schoolwebsite.Models.Teachers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<hr />

<style>

    .login-container {
        margin-top: 5%;
        margin-bottom: 5%;
    }

    .login-form-2 {
        padding: 5%;
        background: #1fa692;
        box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
    }

        .login-form-2 h3 {
            text-align: center;
            color: #fff;
        }

    .login-container form {
        padding: 10%;
    }

    .btnSubmit {
        width: 50%;
        border-radius: 1rem;
        padding: 1.5%;
        border: none;
        cursor: pointer;
    }



    .login-form-2 .ForgetPwd {
        color: #fff;
        font-weight: 600;
        text-decoration: none;
    }
</style>




<div class="col-md-5 login-form-2" id="part-2" style=" margin-left: 30%;">
    <h3 style="margin-bottom:20px;">Teachers Registration Form</h3>
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Name" class="form-control" placeholder="Name" value="" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Email" class="form-control" placeholder="Email Address" value="" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="ContactNum" class="form-control" placeholder="Contact Number" value="" id="contacts"/>
            <span asp-validation-for="ContactNum" class="text-danger"></span>
            <p id="message2"></p>
        </div>
        <div class="form-group">
            <input asp-for="Address" class="form-control" placeholder="Address" value="" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input asp-for="Username" class="form-control" placeholder="User Name" value="" id="name" />
            <span asp-validation-for="Username" class="text-danger"></span>
            <p id="message"></p>
        </div>

        <div class="form-group">
            <input asp-for="password" class="form-control" placeholder="Your Password *" value="" />
            <span asp-validation-for="password" class="text-danger"></span>
        </div>
        <div class="form-group" style="margin-top:30px;">
            <input type="submit" class="btn btn-secondary btn-block" value="Register" id="submit"/>
        </div>

    </form>
</div>


<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>




    




@section Scripts {


    <script type="text/javascript">
    $(document).ready(function () {
        $('#name').keydown(function () {
            $('#message').html("Checking....");
            $('#message').css("color", "blue");
        });

        $('#name').focusout(function () {

            $.post("@Url.Action("Namecheck","Teachers")",
            {
                userdata: $("#name").val()
            },
            function (data) {
                if (data == 0) {
                    $('#message').html("Available ");
                    $('#message').css("color", "green");
                    $("#submit").attr("disabled", false);

                }
                else {
                    $('#message').html("Not Available ");
                    $('#message').css("color", "red");
                    $("#submit").attr("disabled", true);
                }
            });

        });
        $('#contacts').keydown(function () {
            $('#message2').html("Checking....");
            $('#message2').css("color", "blue");

            var contactstring = $("#contacts").val();

            function isNumber(str) {
                if (typeof str != "string") return false // we only process strings!
                // could also coerce to string: str = ""+str
                return !isNaN(str) && !isNaN(parseFloat(str))
            }
            var contact = isNumber(contactstring);

            console.log(contact);
            if (contact ) {

                $('#message2').html("Okay!");
                $('#message2').css("color", "green");

            }
           else {


                $('#message2').html("Number is not correct");
                $('#message2').css("color", "red");
                $("#submit").attr("disabled", true);
            }

        });


    });
    </script>


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoolwebsite/Views/Teachers/Delete.cshtml
@model schoolwebsite.Models.Teachers

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teachers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

schoolwebsite/Views/Teachers/Details.cshtml
@model schoolwebsite.Models.Teachers

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Teachers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.id">Edit</a>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

schoolwebsite/Views/Teachers/Edit.cshtml
@model schoolwebsite.Models.Teachers

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Teachers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNum" class="control-label"></label>
                <input asp-for="ContactNum" class="form-control" />
                <span asp-validation-for="ContactNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoolwebsite/Views/Teachers/Index.cshtml
@model IEnumerable<schoolwebsite.Models.Teachers>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<h1 style="padding-top:50px;">Teachers Registration Details</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Create New</a>
</p>
<table class="display" id="mytable" width="100%" >
    <thead class="thead-dark">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.DateCreated)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.password)
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">

                        <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.id">Edit</a>
                        <a class="btn btn-light" asp-action="Details" asp-route-id="@item.id">Details</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.id">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{

    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            
            var save = ' @TempData["save"]';
            console.log(save);
            if (save == "Data saved Successfully") {
                alertify.success(save);
            }
                           
            
            $('#mytable').DataTable();

            

        });


    </script>
}