schoolwebsite/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using schoolwebsite.Data;
using schoolwebsite.Models;
using SQLitePCL;

namespace schoolwebsite.Controllers
{
    [Authorize]
    public class ResultsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResultsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Results
        public async Task<IActionResult> Index()
        {
            return View(await _context.Results.Include(m=>m.Students).ToListAsync());
        }

        // GET: Results/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var results = await _context.Results
                .FirstOrDefaultAsync(m => m.id == id);
            if (results == null)
            {
                return NotFound();
            }

            return View(results);
        }

        // GET: Results/Create
        public IActionResult Create()
        {
            ViewData["Studentsid"] = new SelectList(_context.Students.ToList(), "id", "Name");
            ViewData["Subjectsid"] = new SelectList(_context.Subjects.ToList(), "id", "Class");
            return View();
        }

        // POST: Results/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Studentsid,year,Subjectsid,Result1,Result2,Result3,Result4,Result5,Result6,Result7,Result8,Result9,Result10,Result11,Result12")] Results results)
        {
            if (ModelState.IsValid)
            {
                _context.Add(results);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Studentsid"] = new SelectList(_context.Students.ToList(), "id", "Name",results.Studentsid);
            return View(results);
        }

        // GET: Results/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var results = await _context.Results.FindAsync(id);
            if (results == null)
            {
                return NotFound();
            }
            return View(results);
        }

        // POST: Results/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Studentsid,Class,Result1,Result2,Result3,Result4,Result5,Result6,Result7,Result8,Result9,Result10,Result11,Result12")] Results results)
        {
            if (id != results.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(results);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResultsExists(results.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(results);
        }

        // GET: Results/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var results = await _context.Results
                .FirstOrDefaultAsync(m => m.id == id);
            if (results == null)
            {
                return NotFound();
            }

            return View(results);
        }

        // POST: Results/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var results = await _context.Results.FindAsync(id);
            _context.Results.Remove(results);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Datatest(int id=1)
        {
            //var result = _context.Results.Include(m => m.Students).Where(m => m.Students.id == id).ToList();
            var result = _context.Results.Include(m=>m.Students).Where(m => m.Students.id == id).ToList();
            return Json(result);
        }

        public IActionResult Datainfo (int userdata)
        {
            //string ID = userdata.ToString();
            var result = _context.Subjects.Where(m => m.id == userdata).ToList();
            return Json(result);
        }
            
        private bool ResultsExists(int id)
        {
            return _context.Results.Any(e => e.id == id);
        }
    }
}

schoolwebsite/Controllers/StudentdetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using schoolwebsite.Data;
using schoolwebsite.Models;

namespace schoolwebsite.Controllers
{
    [Authorize]
    public class StudentdetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        
        public StudentdetailsController(ApplicationDbContext context)
        {
            _context = context;
            
        }
        public IActionResult Index()
        {
            var result = _context.Results.Include(m => m.Subjects).Include(m => m.Students).Include(m => m.Attendances).ToList();
            return View(result);
        }
        public IActionResult Createid(int id)
        {

            var output = _context.Studentdetails.Include(m=>m.Results).Include(m=>m.Students).Where(m => m.Students.id == id).ToList();
            //_context.SaveChanges();
            return Json(output);
        }
        public IActionResult Indextest()
        {
            var result = _context.Results.Include(m => m.Subjects).Include(m => m.Students).ToList();
            return Json(result);
        }
    }
}

schoolwebsite/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using schoolwebsite.Data;
using schoolwebsite.Models;

namespace schoolwebsite.Controllers
{
    
    public class StudentsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;


        public StudentsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;

            
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var result = await _context.Students.ToListAsync();                
                return View(result);
        }

        // GET: Students/Details/5
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,classinfo,roll,section,address,parentscontact,username,dateofbirth,password,Image")] Students students)
        {
            
            if (ModelState.IsValid)
            {
                if (students.Image != null)
                {
                    string datevalue = students.dateofbirth;
                    TempData["save"] = "Submitted Successfully";
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string filename = Path.GetFileNameWithoutExtension(students.Image.FileName);
                    string extension = Path.GetExtension(students.Image.FileName);
                    students.Imagefilename = filename = students.id + extension;
                    string foldername = students.classinfo.ToString();


                    string path2 = wwwRootPath + "\\Images\\" + "\\2020\\" + foldername;

                    if (!Directory.Exists(path2))
                        Directory.CreateDirectory(path2);
                    //Directory.CreateDirectory("wwwRootPath\\Images\\2020\\"+foldername);
                    string path = Path.Combine(wwwRootPath + "/Images/2020", foldername, filename);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await students.Image.CopyToAsync(fileStream);
                    }
                }
                string datevalue1 = students.dateofbirth;
                _context.Add(students);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            return View(students);
        }
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]
        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students.FindAsync(id);
            if (students == null)
            {
                return NotFound();
            }
            return View(students);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,classinfo,roll,section,address,parentscontact,username,password,dateofbirth,Image")] Students students)
        {
            if (id != students.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (students.Image != null)
                    {

                        TempData["save"] = "Submitted Successfully";
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        string filename = Path.GetFileNameWithoutExtension(students.Image.FileName);
                        string extension = Path.GetExtension(students.Image.FileName);
                        students.Imagefilename = filename = students.id + extension;
                        string foldername = students.classinfo.ToString();


                        string path2 = wwwRootPath + "\\Images\\" + "\\2020\\" + foldername;

                        if (!Directory.Exists(path2))
                            Directory.CreateDirectory(path2);
                        //Directory.CreateDirectory("wwwRootPath\\Images\\2020\\"+foldername);
                        string path = Path.Combine(wwwRootPath + "/Images/2020", foldername, filename);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await students.Image.CopyToAsync(fileStream);
                        }
                    }
                    _context.Update(students);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentsExists(students.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["edit"] = "Edited Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(students);
        }

        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students/Delete/5

        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Teacher")]
        [Authorize(Roles = "Headmaster")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var userinfo = await _context.Students.FindAsync(id);
            var imagepath = Path.Combine(_hostEnvironment.WebRootPath, "Images", "2020",userinfo.classinfo.ToString(), userinfo.Imagefilename);
            if (System.IO.File.Exists(imagepath))
                System.IO.File.Delete(imagepath);
            _context.Students.Remove(userinfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        public JsonResult Namecheck(string userdata)
        {
            var search = _context.Students.Any(e => e.username == userdata);
            if (search)
            {
                return Json(1);
            }
            else { return Json(0); }
        }
        public IActionResult Jsonshow(int id)
        {
            return Json(_context.Students.Find(id));
        } 
        private bool StudentsExists(int id)
        {
            return _context.Students.Any(e => e.id == id);
        }
    }
    

           
}

schoolwebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - schoolwebsite</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-fixed navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <div class="d-inline-flex">
                    <img src="~/img/logo.png" asp-append-version="true" width="40" height="40" class="d-inline-block align-top" alt=""><h2>Albert International School</h2>
                </div>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <div class="navbar-nav ml-auto">

                    @if (User.Identity.IsAuthenticated)

                    {
                        if (User.IsInRole("Admin") || User.IsInRole("Teacher") || User.IsInRole("Headmaster"))
                        {
                            <div class="dropdown show mr-lg-2" style="margin-right:3%;">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    More
                                </a>

                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-action="Create" asp-controller="Results">Results</a>
                                    <a class="dropdown-item" asp-action="Create" asp-controller="Subjects">Subjects & Classinfo</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Studentdetails">Students profile with result</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Attendances">Monthly Attendance Input</a>
                                    <a class="dropdown-item" asp-action="Datashow" asp-controller="Attendances">Attendance list</a>
                                    <a class="dropdown-item" asp-action="Index3" asp-controller="Attendances">Short information</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Students">Students Information</a>
                                </div>
                            </div>
                        }
                    }
                    
                    <button type="button" class="btn btn-outline-info mr-lg-2 border-0 rounded" onclick="location.href='@Url.Action("Index","Home")'">Home</button>
                    <button type="button" class="btn btn-outline-info mr-lg-2 border-0 rounded" onclick="location.href='@Url.Action("Create","Students")'">Student's Registration</button>
                    <button type="button" class="btn btn-outline-info mr-lg-2 border-0 rounded" onclick="location.href='@Url.Action("Create","Teachers")'">Teacher's Registration</button>
                    <partial name="_LoginPartial" />
                </div>
                <span class="navbar-text">

                </span>
            </div>
        </nav>
    </header>
    <div class="container-fluid">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:#8adbdb;">
        <div class="container">
            &copy; 2020 - schoolwebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>